# docker-compose.local.yml
services:
  app:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL="http://213.136.80.168"
    env_file:
      - .env.local  # Production environment file
    restart: unless-stopped