export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  ENDPOINTS: {
    USER_ROLES: '/user-roles',
    USERS: '/user',
    AUTH: '/auth',
    MACHINES: '/machine',
    SILOS: '/silo',
    SUPPLIERS: '/supplier-2',
    RAW_MATERIALS: '/raw-material',
    PROCESSES: '/process',
    PRODUCTION_PLANS: '/production-plan',
    DRIVER_FORMS: '/drivers-form',
    RAW_MILK_INTAKE_LAB_TEST: '/raw-milk-intake-lab-test',
    STERI_MILK_TEST_REPORT: '/steri-milk-test-report',
    RAW_MILK_RESULT_SLIP: '/raw-milk-result-slip',
    SILO_MANAGER: {
      SILOS: '/silo-manager/silos',
      CIP_STATUS: '/silo-manager/cip-status',
      TRANSFERS: '/silo-manager/transfers',
    },
    ANALYTICS: {
      COLLECTION_SUMMARY: '/analytics/collection/summary',
      COLLECTION_DETAILS: '/analytics/collection/details',
      FAILED_COLLECTION_SUMMARY: '/analytics/failed-collection/summary',
      SUCCESSFUL_COLLECTION_SUMMARY: '/analytics/successful-collection/summary',
      TESTED_COLLECTION_SUMMARY: '/analytics/tested-collection/summary',
      TESTED_COLLECTION_DETAILS: '/analytics/tested-collection/details',
      UNTESTED_COLLECTION_SUMMARY: '/analytics/untested-collection/summary',
      UNTESTED_COLLECTION_DETAILS: '/analytics/untested-collection/details',
      INTAKE_SUMMARY: '/analytics/intake/summary',
      INTAKE_DETAILS: '/analytics/intake/details',
      CIP: '/analytics/cip',
      PRODUCTION_DETAILS: '/analytics/production/details',
    },
  },
} as const
